sudo: required
services:
 - docker

before_install:
 - docker build -t nikolamir/multi-docker -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true nikolamir/multi-docker npm test 

after_success:
 - docker build -t nikolamir/multi-client ./client
 - docker build -t nikolamir/multi-nginx ./nginx
 - docker build -t nikolamir/multi-server ./server
 - docker build -t nikolamir/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
 - docker push nikolamir/multi-client
 - docker push nikolamir/multi-nginx
 - docker push nikolamir/multi-server
 - docker push nikolamir/multi-worker
 
deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket-name: "elasticbeanstalk-us-east-2-604753490566"
 bucket-path: "docker-multi"
 on:
    branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY