sudo: required
services:
 - docker

before_install:
 - docker build -t nikolamir/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true nikolamir/react-test npm test 

after_success:
 - docker build -t nikolamir/multi-client ./client
 - docker build -t nikolamir/multi-nginx ./nginx
 - docker build -t nikolamir/multi-server ./server
 - docker build -t nikolamir/multi-worker ./worker
 # Log in to the docker CLI
 echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push nikolamir/multi-client
 - docker push nikolamir/multi-nginx
 - docker push nikolamir/multi-server
 - docker push nikolamir/multi-worker
 